### ISSUE TITLE
Password Update Method

### ISSUE THREAD

**Issue by martinjaycyhalum** [martinjaycyhalum/gabc_proto#1]
API Method for changing passwords in-app

**Comment by martinjaycyhalum** [comment]
API Fix is working already added to app controller

**Comment by jamiejavier** [comment]
<img width="415" alt="banner_tnc" src="https://user-images.githubusercontent.com/45158717/48691525-c940d780-ec0d-11e8-8242-10dfa86e24d9.png">

Please use this for the TNC banner
