### ISSUE TITLE
Update Failed

### ISSUE THREAD

**Issue by martinjaycyhalum** [martinjaycyhalum/gabc_proto#11]
![updatefailed](https://user-images.githubusercontent.com/42337852/48838576-bbcd4e00-edc3-11e8-916a-d804933ab707.jpg)

Users are not able to update their profiles in app.

> Checked the API method: `update_customer` and found out that the **P11** and **P12** fields are required

> **P11** and **P2** fields ideally should be able to accept **null** input for these are **optional values** upon **registration**

**Comment by martinjaycyhalum** [comment]
I did necessary work around for this but will need additional assistance from the **CLC API TEAM** to fully integrate

**Comment by paulpanillo** [comment]
Already pushed the changes.
