### ISSUE TITLE
Outdated Pictures in CMS

### ISSUE THREAD

**Issue by KhaiArdamoy** [martinjaycyhalum/gabc_proto#2]
Outdated Pictures in CMS

![mobile_app_5](https://user-images.githubusercontent.com/45159283/48692734-1757da00-ec12-11e8-9991-3ecf55baaf49.jpg)

**Comment by martinjaycyhalum** [comment]
Images are being pulled from the API Dev environment. Will add Paul to this tracker for further help

**Comment by martinjaycyhalum** [comment]
Asking permission to close this ticket Ms. @KhaiArdamoy this is a CLC API issue this is already out of our scope.

**Comment by martinjaycyhalum** [comment]
Images have been updated on the API side
