### ISSUE TITLE
Linked Facebook should show in Settings

### ISSUE THREAD

**Issue by KhaiArdamoy** [martinjaycyhalum/gabc_proto#5]
Linked Facebook should show in Settings

![mobile_app_3](https://user-images.githubusercontent.com/45159283/48693464-80405180-ec14-11e8-8054-5a41d447d1b3.jpg)

**Comment by martinjaycyhalum** [comment]
API can now handle google and facebook ids will update front end accordingly but API still has some issue see Issue #8 for CLC API Requests.

**Comment by martinjaycyhalum** [comment]
CLC API still not returning `google_id` and `facebook_id` on login and email search
