### ISSUE TITLE
Update Sign-up Page text

### ISSUE THREAD

**Issue by KhaiArdamoy** [martinjaycyhalum/gabc_proto#6]
Update Sign-up Page text
![mobile_app_1](https://user-images.githubusercontent.com/45159283/48693505-9d752000-ec14-11e8-9ba7-b589a14ea0cd.jpg)

**Comment by martinjaycyhalum** [comment]
Added Soon to the wording already published and pushed on ota update. Please check Ms. @KhaiArdamoy
