### ISSUE TITLE
Can't log in.

### ISSUE THREAD

**Issue by bryanliu386** [martinjaycyhalum/gabc_proto#9]
Multiple internal users from GABC claiming they can't log in the actual App. Some cases:

1. Some tried using an @goldenabc.com email domain, but the field says invalid email format.

2. Some tried logging in via Facebook but it just loops them back into the log-in screen.

3. Some tried signing up as a new user but says "Email already used", but when they try to log in with the same email, nothing happens.

**Comment by bryanliu386** [comment]
Hi Jaycee, for the GABC domain, what was the issue? Can we open up the field to accept any domain?

Sincerely,

Bryan Liu



On Tue, Nov 20, 2018 at 2:24 PM +0800, "martinjaycyhalum" <notifications@github.com<mailto:notifications@github.com>> wrote:


For the @goldenabc.com domain it's already fixed and it has already been sent as an OTA Update

-

**Comment by bryanliu386** [comment]
Should I also ask people to not log-in via Facebook first?

**Comment by martinjaycyhalum** [comment]
Hi, yes please advise not to login using fb first but they can sign up using facebook details. The problem was with my in app email format validation. I have already did the necessary adjustments to accept the format and have pushed the changes OTA.
